services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    network_mode: host
    extra_hosts:
      - "host.docker.internal:host-gateway"
    init: true
    command: sleep infinity
    volumes:
      - ..:/workspaces/${localWorkspaceFolderBasename}:cached
